apiVersion: backstage.io/v1alpha1
manifestVersion: 0.0.2
kind: Component
metadata:
  id: 1
  namespace: atlas
  name: atlas-backend
  description: |
    Resource manifest app é uma ferramenta para identificar, carregar 
    e salvar informações dos manifests no bigquery.
  gui: false
  sox: true
  pci: false
  processPersonalData: false
  labels:
    lifecycle: production
  tags:
    - python
    - poc
  links:
    - https://important-link.com.br
spec:
  type: website
  lifecycle: production
  owner: project-python@example.com
  authentication: idm 
  authorization: idm
  pagerduty: pd-service-name
  operationalDate: abril
  infraestructure:
    datacenter:
      - server: cloud-name-1
        ip: 129.192.938
        so: linux
      - server: cloud-name-2
        ip: 129.192.939
        so: linux
    cloud:
      - project: project-name-1
        project_id: project-id
  pipeline: 
    url: url-pipeline.com.br
    project: project-name
    pipeline: pipeline-name
  databases:
    - name: db-name-1
      sgbd: mongodb
    - name: db-name-2
      sgbd: mysql
